export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:3000";

export const endpoints = {
  login: "/auth/login",
  me: "/auth/me",
  dashboard: "/dashboard/consolidated",
  projects: "/projects",
  projectById: (projectId: string) => `/projects/${projectId}`,
  projectTasks: (projectId: string) => `/projects/${projectId}/tasks`,
  projectTaskById: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}`,
  projectMilestones: (projectId: string) => `/projects/${projectId}/milestones`,
  projectMilestoneById: (projectId: string, milestoneId: string) => `/projects/${projectId}/milestones/${milestoneId}`,
  projectDependencies: (projectId: string) => `/projects/${projectId}/dependencies`,
  resources: "/resources",
  financialBudgets: "/financial/budgets",
  financialBudgetBaselines: (budgetId: string) => `/financial/budgets/${budgetId}/baselines`,
  financialForecasts: (budgetId: string) => `/financial/budgets/${budgetId}/forecasts`,
  financialActualCosts: (budgetId: string) => `/financial/budgets/${budgetId}/actual-costs`,
  financialSummary: "/financial/summary",
  financialExcelExport: "/financial/excel/export",
  ricExcelExport: "/ric/excel/export",
  ricRiskStatus: (id: string) => `/ric/risks/${id}/status`,
  ricIssueStatus: (id: string) => `/ric/issues/${id}/status`,
  workflowInstanceAction: (instanceId: string) => `/workflows/instances/${instanceId}/actions`,
  workflowInstanceByTenant: (instanceId: string, tenantId: string) => `/workflows/instances/${instanceId}/${tenantId}`,
  workflowInboxPending: "/workflows/inbox/pending",
  workflowInboxHistory: "/workflows/inbox/history",
  aiWeeklyReports: "/ai/weekly-reports",
  aiWeeklyReportById: (reportId: string) => `/ai/weekly-reports/${reportId}`,
  aiWeeklyReportGenerate: "/ai/weekly-reports/generate",
  aiWeeklyReportPublish: (reportId: string) => `/ai/weekly-reports/${reportId}/publish`,
  aiWeeklyReportVersions: (reportId: string) => `/ai/weekly-reports/${reportId}/versions`,
  aiWeeklyReportExportExcel: (reportId: string) => `/ai/weekly-reports/${reportId}/export/excel`,
  aiWeeklyReportExportPdf: (reportId: string) => `/ai/weekly-reports/${reportId}/export/pdf`,
  aiWeeklyReportExportPpt: (reportId: string) => `/ai/weekly-reports/${reportId}/export/ppt`,
  aiRiskSuggestions: "/ai/risk-detection/suggestions",
  aiRiskSuggestionApprove: (suggestionId: string) => `/ai/risk-detection/suggestions/${suggestionId}/approve`,
  aiRiskSuggestionReject: (suggestionId: string) => `/ai/risk-detection/suggestions/${suggestionId}/reject`,
  aiRiskSuggestionPublish: (suggestionId: string) => `/ai/risk-detection/suggestions/${suggestionId}/publish`,
  projectExcelExport: "/projects/excel/export",
  financialRollup: "/financial/rollup",
  ricRollup: "/ric/rollup",
  resourceById: (resourceId: string) => `/resources/${resourceId}`,
  resourceWorkflowSubmit: (resourceId: string) => `/resources/${resourceId}/workflow/submit`,
  resourceWorkflowApprove: (resourceId: string) => `/resources/${resourceId}/workflow/approve`,
  resourceWorkflowReject: (resourceId: string) => `/resources/${resourceId}/workflow/reject`,
  projectWorkflowSubmit: (projectId: string) => `/projects/${projectId}/workflow/submit`,
  projectWorkflowApprove: (projectId: string) => `/projects/${projectId}/workflow/approve`,
  projectWorkflowReject: (projectId: string) => `/projects/${projectId}/workflow/reject`,
  exportDashboard: "/exports/dashboard-summary",
  exportDrilldown: "/exports/dashboard-drilldown"
};
